version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      other-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'astro'
          - '@astrojs/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - '*'
